name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test_windows_msvc:
    name: Test on Windows (MSVC)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Developer Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Latest CMake
        uses: ssrobins/install-cmake@v1

      - name: Restore vcpkg cache
        id: vcpkg-cache
        uses: TAServers/vcpkg-cache@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          VCPKG_FEATURE_FLAGS: "binarycaching"
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
        run: |
          cmake -G Ninja -B build                      `
            --toolchain=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake `
            -DCMAKE_BUILD_TYPE=Release                 `
            -DLINKER_SET_BUILD_EXAMPLE=ON              `
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON    `
            -DCMAKE_CXX_FLAGS="/Zc:inline /Gw /EHsc"   `
            -DCMAKE_EXE_LINKER_FLAGS=LINKER:/OPT:REF
          cmake --build build

      - name: Test
        run: |
          ctest --test-dir build

  test_windows_clang:
    name: Test on Windows (clang-cl)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Developer Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Latest CMake
        uses: ssrobins/install-cmake@v1

      - name: Restore vcpkg cache
        id: vcpkg-cache
        uses: TAServers/vcpkg-cache@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          VCPKG_FEATURE_FLAGS: "binarycaching"
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
        run: |
          cmake -G Ninja -B build                      `
            --toolchain=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake `
            -DCMAKE_CXX_COMPILER=clang-cl              `
            -DCMAKE_BUILD_TYPE=Release                 `
            -DLINKER_SET_BUILD_EXAMPLE=ON              `
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON    `
            -DCMAKE_CXX_FLAGS="/Zc:inline /Gw /EHsc"   `
            -DCMAKE_EXE_LINKER_FLAGS=LINKER:/OPT:REF
          cmake --build build

      - name: Test
        run: |
          ctest --test-dir build

  test_macos:
    name: Test on MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcode Switch
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Restore vcpkg cache
        id: vcpkg-cache
        uses: TAServers/vcpkg-cache@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          VCPKG_FEATURE_FLAGS: "binarycaching"
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
        run: |
          cmake -G Ninja -B build                         \
            --toolchain=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release                    \
            -DLINKER_SET_BUILD_EXAMPLE=ON                 \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON       \
            -DCMAKE_EXE_LINKER_FLAGS=LINKER:-dead_strip
          cmake --build build

      - name: Test
        run: |
          ctest --test-dir build

  test_linux_gcc:
    name: Test on Linux (GCC)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Latest CMake
        uses: ssrobins/install-cmake@v1

      - name: Restore vcpkg cache
        id: vcpkg-cache
        uses: TAServers/vcpkg-cache@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          VCPKG_FEATURE_FLAGS: "binarycaching"
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
        run: |
          cmake -G Ninja -B build                           \
            --toolchain=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release                      \
            -DCMAKE_CXX_COMPILER=g++-14                     \
            -DLINKER_SET_BUILD_EXAMPLE=ON                   \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON         \
            -DCMAKE_EXE_LINKER_FLAGS=LINKER:--gc-sections
          cmake --build build

      - name: Test
        run: |
          ctest --test-dir build

  test_linux_gcc_nolto:
    name: Test on Linux (GCC, No LTO, merge-constants)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Latest CMake
        uses: ssrobins/install-cmake@v1

      - name: Restore vcpkg cache
        id: vcpkg-cache
        uses: TAServers/vcpkg-cache@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          VCPKG_FEATURE_FLAGS: "binarycaching"
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
        run: |
          cmake -G Ninja -B build                           \
            --toolchain=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release                      \
            -DCMAKE_CXX_COMPILER=g++-14                     \
            -DLINKER_SET_BUILD_EXAMPLE=ON                   \
            -DLINKER_SET_TEST_WRITABLE=ON                   \
            -DCMAKE_CXX_FLAGS=-fmerge-all-constants         \
            -DCMAKE_EXE_LINKER_FLAGS=LINKER:--gc-sections
          cmake --build build

      - name: Test
        run: |
          ctest --test-dir build

  test_linux_clang:
    name: Test on Linux (clang)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Latest CMake
        uses: ssrobins/install-cmake@v1

      - name: Restore vcpkg cache
        id: vcpkg-cache
        uses: TAServers/vcpkg-cache@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          VCPKG_FEATURE_FLAGS: "binarycaching"
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
        run: |
          cmake -G Ninja -B build                           \
            --toolchain=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_CXX_COMPILER=clang++-18                 \
            -DCMAKE_BUILD_TYPE=Release                      \
            -DLINKER_SET_BUILD_EXAMPLE=ON                   \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON         \
            -DCMAKE_LINKER_TYPE=LLD                         \
            -DCMAKE_EXE_LINKER_FLAGS=LINKER:--gc-sections
          cmake --build build

      - name: Test
        run: |
          ctest --test-dir build
